apiVersion: 1

datasources:
  - name: MySQL Demo
    type: mysql
    access: proxy
    url: mysql:3306
    database: grafana_demo
    user: grafana
    secureJsonData:
      password: grafana_pass
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    editable: true
